version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo Installing dependencies locally...
      - pip install flask serverless-wsgi -t .
artifacts:
  files:
    - main.py
    - '**/*' # This automatically grabs all your dependency folders
