AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Flask Application Pipeline

Resources:
  FlaskLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: . # Add this exact line to point to your zip root contents
      Handler: main.handler
      Runtime: python3.11
      Timeout: 15
      MemorySize: 512
      Events:
        HttpApiEvent:
          Type: HttpApi
